#!/usr/bin/env python3
"""
Output Linter - helper for the executive-report-design-system skill.

Checks a generated report against the hard constraints and the anti-generic
rules. Everything here is mechanical: the linter cannot tell you whether the
prose is any good, but it can tell you that a CDN link crept in, that an emoji
survived, that a figure was left as a placeholder, or that the last page will
emit a blank sheet.

Run it before handing a report over. A report that fails this is not finished.

Usage:
    python scripts/check_output.py report.html
    python scripts/check_output.py report.html --strict     (warnings fail too)
    python scripts/check_output.py report.html --quiet

Exit codes:
    0  passed
    1  failed
    2  could not run
"""

import argparse
import os
import re
import sys

BANNED_PHRASES = [
    "key insights", "deep dive", "game-changing", "game changing",
    "best-in-class", "seamless integration",
    "generated by ai", "powered by ai", "created with ai",
    "as an ai", "delve into", "unlock the power",
]

# Emoji and pictographic ranges. Deliberately not exhaustive - it catches the
# ones a model actually reaches for.
EMOJI = re.compile(
    "[\U0001F300-\U0001FAFF\U00002600-\U000027BF\U0001F1E6-\U0001F1FF\u2b50\u2705\u274c\u26a0]"
)


class Finding(object):
    def __init__(self, level, rule, detail, hint=None):
        self.level = level          # "error" or "warning"
        self.rule = rule
        self.detail = detail
        self.hint = hint

    def __str__(self):
        mark = "ERROR  " if self.level == "error" else "WARN   "
        out = "%s%s\n         %s" % (mark, self.rule, self.detail)
        if self.hint:
            out += "\n         hint: %s" % self.hint
        # The console this runs on may be cp1252. Never let a stray character in
        # the source document crash the linter.
        return out.encode("ascii", "backslashreplace").decode("ascii")


def strip_comments(html):
    return re.sub(r"<!--.*?-->", "", html, flags=re.DOTALL)


def check_self_contained(html, findings):
    """No network, no external anything. This is the constraint that matters most."""
    body = strip_comments(html)

    # Ignore xmlns and schema identifiers, which are namespaces rather than fetches.
    urls = [
        u for u in re.findall(r"https?://[^\s\"'<>)]+", body)
        if "www.w3.org" not in u and "json-schema.org" not in u
    ]
    if urls:
        findings.append(
            Finding("error", "external URL",
                    "%d found, e.g. %s" % (len(urls), urls[0][:78]),
                    "the report must open with no network; inline everything")
        )

    if re.search(r"<script[^>]+\bsrc\s*=", body, re.I):
        findings.append(
            Finding("error", "external script",
                    "<script src=...> present",
                    "the motion engine is inlined; nothing else may load")
        )

    for match in re.finditer(r"<link[^>]*>", body, re.I):
        tag = match.group(0)
        if re.search(r'rel\s*=\s*["\']?(stylesheet|preconnect|preload|dns-prefetch)', tag, re.I):
            findings.append(
                Finding("error", "external stylesheet or preconnect", tag.strip()[:90],
                        "copy assets/design-system.css into a <style> block instead")
            )

    if "@import" in body:
        findings.append(Finding("error", "@import in CSS", "found in the stylesheet",
                                "inline the rules"))

    for match in re.finditer(r"@font-face\s*{[^}]*}", body, re.I | re.DOTALL):
        if re.search(r"url\s*\(", match.group(0), re.I):
            findings.append(
                Finding("error", "@font-face with a url()", "web font requested",
                        "system fonts only; the stack is in the frozen CSS")
            )

    for lib in ("chart.js", "chartjs", "d3.min", "xlsx.full", "sheetjs", "jquery"):
        if lib in body.lower():
            findings.append(
                Finding("error", "charting or utility library", lib,
                        "charts are inline SVG; no libraries")
            )


def check_anti_generic(html, findings):
    text = re.sub(r"<(script|style)[^>]*>.*?</\1>", " ", html, flags=re.DOTALL | re.I)
    text = re.sub(r"<[^>]+>", " ", text)
    lowered = text.lower()

    for phrase in BANNED_PHRASES:
        if phrase in lowered:
            findings.append(
                Finding("error", "banned phrase", '"%s"' % phrase,
                        "see references/anti-generic-rules.md")
            )

    emoji = EMOJI.findall(text)
    if emoji:
        # Report the codepoints, not the characters. Echoing an emoji to a
        # Windows console raises UnicodeEncodeError and takes the linter down
        # with it - which would turn a lint failure into a crash.
        points = sorted(set("U+%04X" % ord(ch) for ch in emoji))
        findings.append(
            Finding("error", "emoji", "%d found (%s)" % (len(emoji), ", ".join(points[:6])),
                    "no emoji anywhere; use .dot.ok / .warn / .risk for status")
        )

    css = "\n".join(re.findall(r"<style[^>]*>(.*?)</style>", html, re.DOTALL | re.I))
    for value in re.findall(r"border-radius\s*:\s*([0-9.]+)px", css):
        if float(value) > 6:
            findings.append(
                Finding("error", "border-radius too large", "%spx" % value,
                        "4px on cards, 6px on numbered cards; larger reads as an app, not a document")
            )
    if re.search(r"linear-gradient\s*\([^)]*\)", css):
        allowed = len(re.findall(r"linear-gradient", css))
        if allowed > 3:
            findings.append(
                Finding("warning", "gradients", "%d gradient declarations" % allowed,
                        "the design has two: the title fill and the progress bar")
            )
    if re.search(r"text-align\s*:\s*center", css):
        findings.append(
            Finding("warning", "centred text", "text-align: center in the stylesheet",
                    "body copy is left aligned, ragged right")
        )


def check_pages(html, findings):
    # Strip comments first: the reference document mentions the page markup in
    # its own header comment, which would otherwise be counted as a page.
    body = strip_comments(html)

    page_tags = re.findall(r'<section\b[^>]*\bclass\s*=\s*"([^"]*)"', body)
    pages = [c for c in page_tags if re.search(r"(?:^|\s)page(?:\s|$)", c)]
    if not pages:
        findings.append(
            Finding("error", "no pages",
                    'no <section class="page ..."> found',
                    "every sheet is a .page section")
        )
        return

    count = len(pages)

    heads = len(re.findall(r'class="[^"]*\bpage-head\b', body))
    feet = len(re.findall(r'class="[^"]*\bpage-foot\b', body))
    if heads != count:
        findings.append(
            Finding("error", "missing running head",
                    "%d pages but %d page-head elements" % (count, heads),
                    "running heads are in-DOM per page; @page margin boxes do not work in Chromium")
        )
    if feet != count:
        findings.append(
            Finding("error", "missing running foot",
                    "%d pages but %d page-foot elements" % (count, feet),
                    "same reason as the head")
        )

    if "counter-increment" not in body or "pageno" not in body:
        findings.append(
            Finding("error", "no page numbering",
                    "the pageno counter is missing",
                    "body { counter-reset: pageno } and .page { counter-increment: pageno }")
        )

    totals = set(int(n) for n in re.findall(r"of\s+(\d+)\s*<", body))
    if totals and count not in totals:
        findings.append(
            Finding("error", "page total is wrong",
                    "footers say 'of %s' but there are %d pages"
                    % (", ".join(str(t) for t in sorted(totals)), count),
                    "CSS cannot count your own elements; write the total in as a literal")
        )

    if "last-of-type" not in body:
        findings.append(
            Finding("error", "blank trailing page",
                    ".page:last-of-type break-after reset is missing",
                    "without it the last break-after emits an empty sheet")
        )

    if "print-color-adjust" not in body:
        findings.append(
            Finding("error", "backgrounds will not print",
                    "print-color-adjust: exact is missing",
                    "browsers strip backgrounds by default; the warm paper would print white")
        )

    if "@page" in body and re.search(r"@page[^{]*{[^}]*@(top|bottom)-", body):
        findings.append(
            Finding("error", "@page margin boxes",
                    "used for running content",
                    "unsupported in Chromium and WebKit; use in-DOM page-head / page-foot")
        )

    for classes in pages:
        if "palette-" not in classes:
            findings.append(
                Finding("error", "page without a palette",
                        'class="%s"' % classes[:60],
                        "every .page carries one of the four palette classes")
            )
            break


def check_figures(html, findings):
    values = re.findall(r'class="[^"]*\bkpi-value\b[^"]*"[^>]*>([^<]{0,40})<', html)
    for value in values:
        stripped = value.strip()
        if not stripped:
            findings.append(
                Finding("error", "empty figure", "a kpi-value is blank",
                        "write the real final figure into the markup")
            )
        elif stripped in ("0", "0.0", "-", "TBC", "TBD", "N/A", "X"):
            findings.append(
                Finding("error", "placeholder figure", '"%s"' % stripped,
                        "the motion engine animates to whatever is in the markup, so a placeholder animates to a placeholder")
            )
        elif not any(ch.isdigit() for ch in stripped):
            findings.append(
                Finding("warning", "figure has no digit", '"%s"' % stripped,
                        "it will render but will not animate")
            )

    if re.search(r'class="[^"]*\bbar-fill\b', html):
        widths = re.findall(r'class="[^"]*\bbar-fill\b[^"]*"[^>]*style="[^"]*width\s*:\s*([0-9.]+)%', html)
        bars = len(re.findall(r'class="[^"]*\bbar-fill\b', html))
        if len(widths) < bars:
            findings.append(
                Finding("error", "bar without a width",
                        "%d bars, %d widths" % (bars, len(widths)),
                        'each .bar-fill needs style="width:NN%"')
            )
        if widths and max(float(w) for w in widths) < 99.0:
            findings.append(
                Finding("warning", "no full-length bar",
                        "the longest bar is %.0f%%" % max(float(w) for w in widths),
                        "widths are share of the largest item, so one bar should be 100%")
            )


def check_accessibility(html, findings):
    for match in re.finditer(r"<svg\b[^>]*>", html, re.I):
        tag = match.group(0)
        if "aria-label" not in tag and 'role="img"' not in tag:
            findings.append(
                Finding("warning", "chart without a text alternative",
                        "an <svg> has no aria-label",
                        "a chart that cannot be read aloud is invisible to a screen reader")
            )
            break

    if "prefers-reduced-motion" not in html and "js-motion" in html:
        findings.append(
            Finding("error", "motion without a reduced-motion escape",
                    "prefers-reduced-motion is not honoured",
                    "it is in the frozen CSS; it was removed or the CSS was edited")
        )

    if re.search(r"<script", html, re.I) and "beforeprint" not in html:
        findings.append(
            Finding("warning", "animation may print mid-flight",
                    "no beforeprint handler",
                    "figures must snap to final before the sheet is rendered")
        )


def main():
    parser = argparse.ArgumentParser(
        description="Lint a generated report against the design-system constraints."
    )
    parser.add_argument("document", help="path to the generated .html")
    parser.add_argument("--strict", action="store_true", help="treat warnings as failures")
    parser.add_argument("--quiet", action="store_true", help="print nothing on a clean pass")
    args = parser.parse_args()

    if not os.path.isfile(args.document):
        sys.stdout.write("cannot read %s\n" % args.document)
        return 2

    with open(args.document, "r", encoding="utf-8") as handle:
        html = handle.read()

    findings = []
    check_self_contained(html, findings)
    check_anti_generic(html, findings)
    check_pages(html, findings)
    check_figures(html, findings)
    check_accessibility(html, findings)

    errors = [f for f in findings if f.level == "error"]
    warnings = [f for f in findings if f.level == "warning"]

    if findings:
        sys.stdout.write("%s\n\n" % args.document)
        for finding in errors + warnings:
            sys.stdout.write("%s\n\n" % finding)
        sys.stdout.write("%d error%s, %d warning%s\n" % (
            len(errors), "" if len(errors) == 1 else "s",
            len(warnings), "" if len(warnings) == 1 else "s",
        ))
    elif not args.quiet:
        body = strip_comments(html)
        tags = re.findall(r'<section\b[^>]*\bclass\s*=\s*"([^"]*)"', body)
        pages = len([c for c in tags if re.search(r"(?:^|\s)page(?:\s|$)", c)])
        sys.stdout.write("PASS     %s\n         %d pages, self-contained, no generic tells\n"
                         % (args.document, pages))

    if errors:
        return 1
    if warnings and args.strict:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
